export const GET_ADMIN_PROFILE = 'GET_ADMIN_PROFILE'
export const GET_ADMIN_PROFILE_SUCCESSFUL = 'GET_ADMIN_PROFILE_SUCCESSFUL'
export const GET_ADMIN_PROFILE_FAILED = 'GET_ADMIN_PROFILE_FAILED'

export const UPDATE_ADMIN_PROFILE = 'UPDATE_ADMIN_PROFILE'
export const UPDATE_ADMIN_PROFILE_SUCCESSFUL = 'UPDATE_ADMIN_PROFILE_SUCCESSFUL'
export const UPDATE_ADMIN_PROFILE_FAILED = 'UPDATE_ADMIN_PROFILE_FAILED'
