export const REQUEST_LOGIN = "REQUEST_LOGIN";
export const REQUEST_LOGIN_SUCCESSFUL = "REQUEST_LOGIN_SUCCESSFUL";
export const REQUEST_LOGIN_FAILED = "REQUEST_LOGIN_FAILED";


export const REQUEST_REGISTER = "REQUEST_REGISTER";
export const REQUEST_REGISTER_SUCCESSFUL = "REQUEST_REGISTER_SUCCESSFUL";
export const REQUEST_REGISTER_FAILED = "REQUEST_REGISTER_FAILED";