export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_LOGIN_SUCCESSFUL = 'REQUEST_LOGIN_SUCCESSFUL'
export const REQUEST_LOGIN_FAILED = 'REQUEST_LOGIN_FAILED'

export const REQUEST_REGISTER = 'REQUEST_REGISTER'
export const REQUEST_REGISTER_SUCCESSFUL = 'REQUEST_REGISTER_SUCCESSFUL'
export const REQUEST_REGISTER_FAILED = 'REQUEST_REGISTER_FAILED'

export const REQUEST_REGISTER_ADMIN = 'REQUEST_REGISTER_ADMIN'
export const REQUEST_REGISTER_ADMIN_SUCCESSFUL =
  'REQUEST_REGISTER_ADMIN_SUCCESSFUL'
export const REQUEST_REGISTER_ADMIN_FAILED = 'REQUEST_REGISTER_ADMIN_FAILED'

export const REQUEST_LOGIN_ADMIN = 'REQUEST_LOGIN_ADMIN'
export const REQUEST_LOGIN_ADMIN_SUCCESSFUL = 'REQUEST_LOGIN_ADMIN_SUCCESSFUL'
export const REQUEST_LOGIN_ADMIN_FAILED = 'REQUEST_LOGIN_ADMIN_FAILED'

export const ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT'
export const ACTIVATE_ACCOUNT_SUCCESSFUL = 'ACTIVATE_ACCOUNT_SUCCESSFUL'
export const ACTIVATE_ACCOUNT_FAILED = 'ACTIVATE_ACCOUNT_FAILED'




export const RESEND_TOKEN = "RESEND_TOKEN"
export const RESEND_TOKEN_SUCCESSFUL = "RESEND_TOKEN_SUCCESSFUL"
export const RESEND_TOKEN_FAILED = "RESEND_TOKEN_FAILED"



export const CLEAR_AUTH = "CLEAR_AUTH"