export const VERIFY_COUPON_CODE = 'VERIFY_COUPON_CODE'
export const VERIFY_COUPON_CODE_SUCCESSFUL = 'VERIFY_COUPON_CODE_SUCCESSFUL'
export const VERIFY_COUPON_CODE_FAILED = 'VERIFY_COUPON_CODE_FAILED'

export const CREATE_COUPON_CODE = 'CREATE_COUPON_CODE'
export const CREATE_COUPON_CODE_SUCCESSFUL = 'CREATE_COUPON_CODE_SUCCESSFUL'
export const CREATE_COUPON_CODE_FAILED = 'CREATE_COUPON_CODE_FAILED'

export const GET_COMPANY_COUPON = 'GET_COMPANY_COUPON'
export const GET_COMPANY_COUPON_SUCCESSFUL = 'GET_COMPANY_COUPON_SUCCESSFUL'
export const GET_COMPANY_COUPON_FAILED = 'GET_COMPANY_COUPON_FAILED'

export const GET_ALL_COUPONS = 'GET_ALL_COUPONS'
export const GET_ALL_COUPONS_SUCCESSFUL = 'GET_ALL_COUPONS_SUCCESSFUL'
export const GET_ALL_COUPONS_FAILED = 'GET_ALL_COUPONS_FAILED'