export const FETCH_ALL_EMPLOYEES = 'FETCH_ALL_EMPLOYEES'
export const FETCH_ALL_EMPLOYEES_SUCCESSFUL = 'FETCH_ALL_EMPLOYEES_SUCCESSFUL'
export const FETCH_ALL_EMPLOYEES_FAILED = 'FETCH_ALL_EMPLOYEES_FAILED'

// ActionTypes
export const FETCH_ADMIN_EMPLOYEES = 'FETCH_ADMIN_EMPLOYEES'
export const FETCH_ADMIN_EMPLOYEES_SUCCESSFUL =
  'FETCH_ADMIN_EMPLOYEES_SUCCESSFUL'
export const FETCH_ADMIN_EMPLOYEES_FAILED = 'FETCH_ADMIN_EMPLOYEES_FAILED'

export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'
export const CREATE_EMPLOYEE_SUCCESSFUL = 'CREATE_EMPLOYEE_SUCCESSFUL'
export const CREATE_EMPLOYEE_FAILED = 'CREATE_EMPLOYEE_FAILED'

export const UPDATE_EMPLOYEE_STATUS = 'UPDATE_EMPLOYEE_STATUS'
export const UPDATE_EMPLOYEE_STATUS_SUCCESSFUL =
  'UPDATE_EMPLOYEE_STATUS_SUCCESSFUL'
export const UPDATE_EMPLOYEE_STATUS_FAILED = 'UPDATE_EMPLOYEE_STATUS_FAILED'

export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const DELETE_EMPLOYEE_SUCCESSFUL = 'DELETE_EMPLOYEE_SUCCESSFUL'
export const DELETE_EMPLOYEE_FAILED = 'DELETE_EMPLOYEE_FAILED'


export const GET_AGENT = "GET_AGENT";
export const GET_AGENT_SUCCESSFUL = "GET_AGENT_SUCCESSFUL"
export const GET_AGENT_FAILED = "GET_AGENT_FAILED";




export const CLEAR = 'CLEAR'
