export const REQUEST_TOUR = 'REQUEST_TOUR'
export const REQUEST_TOUR_SUCCESSFUL = 'REQUEST_TOUR_SUCCESSFUL'
export const REQUEST_TOUR_FAILED = 'REQUEST_TOUR_FAILED'

export const MESSAGE_AGENT = 'MESSAGE_AGENT'
export const MESSAGE_AGENT_SUCCESSFUL = 'MESSAGE_AGENT_SUCCESSFUL'
export const MESSAGE_AGENT_FAILED = 'MESSAGE_AGENT_FAILED'
