export const GET_NOTIFICATION = 'GET_NOTIFICATION'
export const GET_NOTIFICATION_SUCCESSFUL = 'GET_NOTIFICATION_SUCCESSFUL'
export const GET_NOTIFICATION_FAILED = 'GET_NOTIFICATION_FAILED'

export const UPDATE_NOTIFICATION = 'UPDATE_NOTIFICATION'
export const UPDATE_NOTIFICATION_SUCCESSFUL = 'UPDATE_NOTIFICATION_SUCCESSFUL'
export const UPDATE_NOTIFICATION_FAILED = 'UPDATE_NOTIFICATION_FAILED'
