export const FETCH_USER_ORDER = "FETCH_USER_ORDER";
export const FETCH_USER_ORDER_SUCCESSFUL = "FETCH_USER_ORDER_SUCCESSFUL";
export const FETCH_USER_ORDER_FAILED = "FETCH_USER_ORDER_FAILED";




export const FETCH_ADMIN_ORDER = "FETCH_ADMIN_ORDER";
export const FETCH_ADMIN_ORDER_SUCCESSFUL = "FETCH_ADMIN_ORDER_SUCCESSFUL";
export const FETCH_ADMIN_ORDER_FAILED = "FETCH_ADMIN_ORDER_FAILED";





export const CREATE_USER_ORDER = "CREATE_USER_ORDER";
export const CREATE_USER_ORDER_SUCCESSFUL = "CREATE_USER_ORDER_SUCCESSFUL";
export const CREATE_USER_ORDER_FAILED = "CREATE_USER_ORDER_FAILED";





export const UPDATE_USER_ORDER = "UPDATE_USER_ORDER";
export const UPDATE_USER_ORDER_SUCCESSFUL = "UPDATE_USER_ORDER_SUCCESSFUL";
export const UPDATE_USER_ORDER_FAILED = "UPDATE_USER_ORDER_FAILED";