export const FETCH_PROPERTIES = "FETCH_PROPERTIES"
export const FETCH_PROPERTIES_SUCCESSFUL = "FETCH_PROPERTIES_SUCCESSFUL"
export const FETCH_PROPERTIES_FAILED = "FETCH_PROPERTIES_FAILED"




export const FETCH_MY_PROPERTIES = "FETCH_MY_PROPERTIES"
export const FETCH_MY_PROPERTIES_SUCCESSFUL = "FETCH_MY_PROPERTIES_SUCCESSFUL"
export const FETCH_MY_PROPERTIES_FAILED = "FETCH_MY_PROPERTIES_FAILED"




export const CREATE_PROPERTIES = "CREATE_PROPERTIES"
export const CREATE_PROPERTIES_SUCCESSFUL = "CREATE_PROPERTIES_SUCCESSFUL"
export const CREATE_PROPERTIES_FAILED = "CREATE_PROPERTIES_FAILED"





export const FETCH_PROPERTY_DETAILS = "FETCH_PROPERTY_DETAILS"
export const FETCH_PROPERTY_DETAILS_SUCCESSFUL = "FETCH_PROPERTY_DETAILS_SUCCESSFUL"
export const FETCH_PROPERTY_DETAILS_FAILED = "FETCH_PROPERTY_DETAILS_FAILED"

