export const FETCH_PROPERTY_TYPE = 'FETCH_PROPERTY_TYPE'
export const FETCH_PROPERTY_TYPE_SUCCESSFUL = 'FETCH_PROPERTY_TYPE_SUCCESSFUL'
export const FETCH_PROPERTY_TYPE_FAILED = 'FETCH_PROPERTY_TYPE_FAILED'
