export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESSFUL = "UPDATE_USER_PROFILE_SUCCESSFUL";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";


export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
export const UPDATE_PASSWORD_SUCCESSFUL = "UPDATE_PASSWORD_SUCCESSFUL";
export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";



export const GET_USER_DETAIL = "GET_USER_DETAIL"
export const GET_USER_DETAIL_SUCCESSFUL = "GET_USER_DETAIL_SUCCESSFUL"
export const GET_USER_DETAIL_FAILED = "GET_USER_DETAIL_FAILED"